environment:
  matrix:
    -nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

  test_script:
  #output useful info for debugging
   - node --version
   - npm --version
    # run tests
    - npm test

    # Dont actually build.
    build: off
